### ISSUE TITLE
dependended module "kernel"

### ISSUE THREAD

**Issue by bruce803** [mstrazar/mklaren#2]
Hi

I am trying to install mklaren. It seems that mklaren depend on "kernel". Can you please tell me more about the "kernel" module?  Does "kernel" refers to another required module for mklaren or the subdirectory of mklaren?

The details:
root@e1ace731c68a ~
  # pip install mklaren                                                                                                                             !493
Collecting mklaren
  Downloading http://mirrors.aliyun.com/pypi/packages/08/d8/8adab90e7e5b85ccc46da94a20bcce1d397b0c85474a0eee515bfc4d4890/mklaren-1.0.tar.gz
Building wheels for collected packages: mklaren
  Running setup.py bdist_wheel for mklaren ... done
  Stored in directory: /root/.cache/pip/wheels/48/6a/9a/aed7546afe5300dbcd0fb7cfcf03d37ff592acb4b3e6bb5973
Successfully built mklaren
Installing collected packages: mklaren
Successfully installed mklaren-1.0
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

root@e1ace731c68a ~
  # python                                                                                                                                          !494
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mklaren
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/anaconda3/lib/python3.5/site-packages/mklaren/__init__.py", line 1, in <module>
    import kernel
ImportError: No module named 'kernel'

**Comment by mstrazar** [comment]
Dear Bruce, thank you for your feedback. We have repaired the package structure, so the core components should now be installable. 

Some pakcages need to be installed manually to run all the examples: matplotlib, GPy, Oct2Py (with octave interpreter).

Mklaren was tested on python 2.7 so far. We will add Python 3 compatibility in the near future.
